export const styles = {
  page: {
    fontFamily: "Arial",
    minHeight: "100vh",
    background: "#f5f7fb",
    padding: "32px 16px",
  },
  container: {
    maxWidth: "1100px",
    margin: "0 auto",
  },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  title: {
    margin: 0,
    fontSize: "32px",
    fontWeight: 800,
    color: "#111827",
  },
  subtitle: {
    margin: "8px 0 0",
    color: "#6b7280",
    fontSize: "15px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  section: {
    background: "#fff",
    borderRadius: "18px",
    padding: "24px",
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.06)",
  },
  sectionTitle: {
    margin: "0 0 18px",
    fontSize: "20px",
    fontWeight: 700,
    color: "#111827",
  },
  subTitle: {
    marginTop: "20px",
    marginBottom: "12px",
    fontSize: "16px",
    color: "#111827",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "16px",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  labelText: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#374151",
  },
  input: {
    height: "46px",
    borderRadius: "12px",
    border: "1px solid #d1d5db",
    padding: "0 14px",
    fontSize: "15px",
    outline: "none",
    background: "#fff",
  },
  textarea: {
    borderRadius: "12px",
    border: "1px solid #d1d5db",
    padding: "14px",
    fontSize: "15px",
    resize: "vertical",
    outline: "none",
  },
  uploadBox: {
    minHeight: "140px",
    border: "2px dashed #c7d2fe",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    cursor: "pointer",
    color: "#4338ca",
    background: "#eef2ff",
    textAlign: "center",
    padding: "20px",
  },
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
    marginTop: "18px",
  },
  uploadedGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
    marginTop: "12px",
  },
  previewImage: {
    width: "100%",
    height: "160px",
    objectFit: "cover",
    borderRadius: "14px",
    border: "1px solid #e5e7eb",
  },
  imageAnalyzeBtn: {
    border: "1px solid #d1d5db",
    borderRadius: "14px",
    background: "#fff",
    padding: "8px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    fontWeight: 700,
    color: "#111827",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    flexWrap: "wrap",
  },
  actionsLeft: {
    display: "flex",
    justifyContent: "flex-start",
    marginTop: "16px",
    marginBottom: "12px",
  },
  primaryBtn: {
    border: "none",
    borderRadius: "12px",
    padding: "14px 22px",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
    color: "#fff",
    background: "#2563eb",
  },
  secondaryBtn: {
    border: "1px solid #d1d5db",
    borderRadius: "12px",
    padding: "14px 22px",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
    background: "#fff",
    color: "#111827",
  },
  predictBtn: {
    border: "none",
    borderRadius: "12px",
    padding: "14px 22px",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
    color: "#fff",
    background: "#7c3aed",
  },
  helperText: {
    color: "#6b7280",
    fontSize: "14px",
    marginBottom: "14px",
  },
  errorBox: {
    background: "#fef2f2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    borderRadius: "12px",
    padding: "14px 16px",
    whiteSpace: "pre-line",
  },
  successBox: {
    background: "#ecfdf5",
    color: "#047857",
    border: "1px solid #a7f3d0",
    borderRadius: "12px",
    padding: "14px 16px",
  },
  infoBox: {
    background: "#eff6ff",
    color: "#1d4ed8",
    border: "1px solid #bfdbfe",
    borderRadius: "12px",
    padding: "14px 16px",
  },
  warningBox: {
    background: "#fff7ed",
    color: "#9a3412",
    border: "1px solid #fdba74",
    borderRadius: "12px",
    padding: "14px 16px",
    marginBottom: "14px",
  },
  priceInsightBox: {
    marginTop: "16px",
    borderRadius: "12px",
    padding: "14px 16px",
    border: "1px solid",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  priceHigh: {
    background: "#fff7ed",
    borderColor: "#fdba74",
    color: "#9a3412",
  },
  priceLow: {
    background: "#eff6ff",
    borderColor: "#93c5fd",
    color: "#1d4ed8",
  },
  priceOk: {
    background: "#ecfdf5",
    borderColor: "#86efac",
    color: "#047857",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    zIndex: 1000,
  },
  modal: {
    width: "100%",
    maxWidth: "520px",
    background: "#fff",
    borderRadius: "18px",
    padding: "24px",
    boxShadow: "0 20px 50px rgba(0,0,0,0.2)",
  },
  analysisModal: {
    width: "100%",
    maxWidth: "900px",
    maxHeight: "90vh",
    overflowY: "auto",
    background: "#fff",
    borderRadius: "18px",
    padding: "24px",
    boxShadow: "0 20px 50px rgba(0,0,0,0.2)",
  },
  modalTitle: {
    margin: "0 0 10px",
    fontSize: "22px",
    color: "#111827",
  },
  modalText: {
    margin: "0 0 18px",
    color: "#6b7280",
    lineHeight: 1.5,
  },
  modalActionsColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  linkBtn: {
    border: "none",
    background: "transparent",
    color: "#4b5563",
    cursor: "pointer",
    fontWeight: 600,
    padding: "8px",
  },
  annotatedImage: {
    width: "100%",
    maxHeight: "600px",
    objectFit: "contain",
    borderRadius: "14px",
    border: "1px solid #e5e7eb",
    background: "#111827",
    marginBottom: "16px",
  },
  analysisInfo: {
    display: "flex",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "16px",
    color: "#111827",
  },
  detectionList: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "14px",
    marginBottom: "16px",
  },
  detectionItem: {
    marginTop: "8px",
    color: "#374151",
  },
  batchSummaryBox: {
    marginTop: "20px",
    background: "#ecfdf5",
    color: "#047857",
    border: "1px solid #a7f3d0",
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  batchResultGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
    marginTop: "18px",
  },
  batchResultCard: {
    border: "1px solid #e5e7eb",
    borderRadius: "14px",
    padding: "8px",
    background: "#fff",
    cursor: "pointer",
  },
  previewCard: {
  position: "relative",
  borderRadius: "14px",
  overflow: "hidden",
},

removeImageBtn: {
  position: "absolute",
  top: "8px",
  right: "8px",
  border: "none",
  borderRadius: "10px",
  padding: "8px 10px",
  background: "#dc2626",
  color: "#fff",
  cursor: "pointer",
  fontWeight: 700,
  fontSize: "13px",
},
};
export default styles;
